apiVersion: batch/v1
kind: Job
metadata:
 name: client
spec:
 template:
  spec:
   containers:
    - name: client
      image:
      command: ["python","app.py"]
    restartPolicy: OnFailure